FROM ubuntu:18.04

#This is a base image for miniconda 3.
#No additional packages are installed.
#
#Build:
#docker build -t mfreitas/dsclub_base -f Dockerfile_Miniconda3_4.5.11 .
#
#Run:
#docker run -it -v $PWD:/data mfreitas/dsclub_base /bin/bash
#
#Clean images and containers (will delete all images and containers)
#docker container prune
#docker image prune -a

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh
RUN /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda config --add channels defaults &&  \
    conda config --add channels conda-forge && \
    conda config --add channels bioconda

COPY environment.yml environment.yml
RUN conda env update -f environment.yml
EXPOSE 8888
